gui:
  language: 'en'
  showIcons: true
  showCommandLog: false
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue
    selectedRangeBgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - white
  commitLength:
    show: true
git:
  log:
    showGraph: 'always'
    showWholeGraph: true
