# Aliases
alias g="git"
alias lg="lazygit"
alias ls="eza -alF --color=always"
alias ll="eza -al --group-directories-first"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias vim="nvim"
alias d="docker"
alias ..="cd .."
alias bc="bc -l"
alias tf="terraform"
alias kc="kubectl"
